name: OnPullRequest
permissions: read-all

on:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.step1.outputs.runner }}
    steps:
      - name: Check repository
        id: step1
        run: |
          if [ "${{ github.repository }}" == 'intel/trustauthority-samples' ]; then
            echo "runner=ubuntu-latest" >> $GITHUB_OUTPUT
          else
            echo "runner=self-hosted" >> $GITHUB_OUTPUT
          fi

  build:
    needs: [setup]
    runs-on: ${{ needs.setup.outputs.runner }}
    env:
      http_proxy: ${{ secrets.HTTP_PROXY }}
      https_proxy: ${{ secrets.HTTPS_PROXY }}
      no_proxy: ${{ secrets.NO_PROXY }}
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.23.6'

      - name: Style Checker
        run: |
          gofmt -l .
          if [[ $(gofmt -l . | wc -l) -gt 0 ]]; then
             echo "Atleast 1 file need formatting"
             exit 1
          fi

      - name: Build workload
        run: make -C tdx-ml-workload trustauthority-demo
